name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Please describe the suggested changes.
  - type: input
    id: file
    attributes:
      label: Affected File
      description: Which file needs improvement? (e.g., README.md, or a script’s docstring)
      placeholder: e.g., README.md
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or improvement needed in the documentation.
      placeholder: The README is unclear about [specific section]. It should include [suggestion].
    validations:
      required: true
  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: Suggest specific changes or provide revised text.
      placeholder: |
        Current text: "..."
        Suggested text: "..."
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other context or references.
    validations:
      required: false