name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details to help us understand your idea.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you’re proposing.
      placeholder: I suggest adding a new feature for [description] to [purpose].
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain the problem this solves or its real-world application.
      placeholder: This feature would help users [benefit] by [example].
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: Provide a rough idea of how this could be implemented (code, libraries, etc.).
      placeholder: |
        ```python
        # Example code for the proposed feature
        ```
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other context, references, or examples.
    validations:
      required: false